// Generated logical-name to registered host-stub mapping.
// Resolver calls take addresses only; no CUDA initialization or launches.
static const std::array<FKernelSymbolEntry, 81>& GetKernelSymbolTable()
{
	static const std::array<FKernelSymbolEntry, 81> Table{{
		{"channel_projection_c512_to_c1024_fp16",
		 reinterpret_cast<const void*>(&channel_projection_c512_to_c1024_fp16)},
		{"channel_projection_c512_to_c1024_fp8",
		 reinterpret_cast<const void*>(&channel_projection_c512_to_c1024_fp8)},
		{"completion_counter_clear", reinterpret_cast<const void*>(&completion_counter_clear)},
		{"decoder_upsample_c1024_to_c512_fp16",
		 reinterpret_cast<const void*>(&decoder_upsample_c1024_to_c512_fp16)},
		{"decoder_upsample_c1024_to_c512_fp8",
		 reinterpret_cast<const void*>(&decoder_upsample_c1024_to_c512_fp8)},
		{"global_attention_chained_c1024_fp16",
		 reinterpret_cast<const void*>(&global_attention_chained_c1024_fp16)},
		{"global_attention_chained_c1024_fp8",
		 reinterpret_cast<const void*>(&global_attention_chained_c1024_fp8)},
		{"global_ffn_contract_c1024_fp16", reinterpret_cast<const void*>(&global_ffn_contract_c1024_fp16)},
		{"global_ffn_contract_c1024_fp8", Resolve_global_ffn_contract_c1024_fp8()},
		{"global_ffn_expand_c1024_fp16", reinterpret_cast<const void*>(&global_ffn_expand_c1024_fp16)},
		{"global_ffn_expand_c1024_fp8", reinterpret_cast<const void*>(&global_ffn_expand_c1024_fp8)},
		{"global_projection_c1024_fp16", reinterpret_cast<const void*>(&global_projection_c1024_fp16)},
		{"global_projection_c1024_fp8", Resolve_global_projection_c1024_fp8()},
		{"global_qkv_c1024_fp16", reinterpret_cast<const void*>(&global_qkv_c1024_fp16)},
		{"global_qkv_c1024_fp8", reinterpret_cast<const void*>(&global_qkv_c1024_fp8)},
		{"input_preprocess_window_c32_fp16",
		 reinterpret_cast<const void*>(&input_preprocess_window_c32_fp16)},
		{"input_preprocess_window_c32_fp8", reinterpret_cast<const void*>(&input_preprocess_window_c32_fp8)},
		{"input_preprocess_window_downsample_c32_fp16",
		 reinterpret_cast<const void*>(&input_preprocess_window_downsample_c32_fp16)},
		{"input_preprocess_window_downsample_c32_fp8",
		 reinterpret_cast<const void*>(&input_preprocess_window_downsample_c32_fp8)},
		{"output_window_postprocess_c32_fp16",
		 reinterpret_cast<const void*>(&output_window_postprocess_c32_fp16)},
		{"output_window_postprocess_c32_fp8",
		 reinterpret_cast<const void*>(&output_window_postprocess_c32_fp8)},
		{"repack_1d_to_2d_c1024_fp16", Resolve_repack_1d_to_2d_c1024_fp16()},
		{"repack_1d_to_2d_c1024_fp8", Resolve_repack_1d_to_2d_c1024_fp8()},
		{"repack_2d_to_1d_c1024_fp16", Resolve_repack_2d_to_1d_c1024_fp16()},
		{"repack_2d_to_1d_c1024_fp8", Resolve_repack_2d_to_1d_c1024_fp8()},
		{"window_attention_projection_c512_fp16", Resolve_window_attention_projection_c512_fp16()},
		{"window_attention_projection_c512_fp8", Resolve_window_attention_projection_c512_fp8()},
		{"window_attention_projection_output_view_c512_fp16",
		 reinterpret_cast<const void*>(&window_attention_projection_output_view_c512_fp16)},
		{"window_attention_projection_output_view_c512_fp8",
		 reinterpret_cast<const void*>(&window_attention_projection_output_view_c512_fp8)},
		{"window_attention_projection_pool_c512_fp16",
		 reinterpret_cast<const void*>(&window_attention_projection_pool_c512_fp16)},
		{"window_attention_projection_pool_c512_fp8",
		 reinterpret_cast<const void*>(&window_attention_projection_pool_c512_fp8)},
		{"window_block_c128_downsample_fp16", Resolve_window_block_c128_downsample_fp16()},
		{"window_block_c128_downsample_fp8", Resolve_window_block_c128_downsample_fp8()},
		{"window_block_c128_fp16", Resolve_window_block_c128_fp16()},
		{"window_block_c128_fp8", Resolve_window_block_c128_fp8()},
		{"window_block_c128_input_view_fp16", Resolve_window_block_c128_input_view_fp16()},
		{"window_block_c128_input_view_fp8", Resolve_window_block_c128_input_view_fp8()},
		{"window_block_c128_output_view_fp16", Resolve_window_block_c128_output_view_fp16()},
		{"window_block_c128_output_view_fp8", Resolve_window_block_c128_output_view_fp8()},
		{"window_block_c128_upsample_fp16", Resolve_window_block_c128_upsample_fp16()},
		{"window_block_c128_upsample_fp8", Resolve_window_block_c128_upsample_fp8()},
		{"window_block_c256_downsample_fp16", Resolve_window_block_c256_downsample_fp16()},
		{"window_block_c256_downsample_fp8", Resolve_window_block_c256_downsample_fp8()},
		{"window_block_c256_fp16", Resolve_window_block_c256_fp16()},
		{"window_block_c256_fp8", Resolve_window_block_c256_fp8()},
		{"window_block_c256_input_view_fp16", Resolve_window_block_c256_input_view_fp16()},
		{"window_block_c256_input_view_fp8", Resolve_window_block_c256_input_view_fp8()},
		{"window_block_c256_output_view_fp16", Resolve_window_block_c256_output_view_fp16()},
		{"window_block_c256_output_view_fp8", Resolve_window_block_c256_output_view_fp8()},
		{"window_block_c256_upsample_fp16", Resolve_window_block_c256_upsample_fp16()},
		{"window_block_c256_upsample_fp8", Resolve_window_block_c256_upsample_fp8()},
		{"window_block_c32_downsample_fp16",
		 reinterpret_cast<const void*>(&window_block_c32_downsample_fp16)},
		{"window_block_c32_downsample_fp8", reinterpret_cast<const void*>(&window_block_c32_downsample_fp8)},
		{"window_block_c32_fp16", Resolve_window_block_c32_fp16()},
		{"window_block_c32_fp8", Resolve_window_block_c32_fp8()},
		{"window_block_c32_input_view_fp16", Resolve_window_block_c32_input_view_fp16()},
		{"window_block_c32_input_view_fp8", Resolve_window_block_c32_input_view_fp8()},
		{"window_block_c32_output_view_fp16",
		 reinterpret_cast<const void*>(&window_block_c32_output_view_fp16)},
		{"window_block_c32_output_view_fp8",
		 reinterpret_cast<const void*>(&window_block_c32_output_view_fp8)},
		{"window_block_c32_upsample_fp16", reinterpret_cast<const void*>(&window_block_c32_upsample_fp16)},
		{"window_block_c32_upsample_fp8", reinterpret_cast<const void*>(&window_block_c32_upsample_fp8)},
		{"window_block_c64_downsample_fp16",
		 reinterpret_cast<const void*>(&window_block_c64_downsample_fp16)},
		{"window_block_c64_downsample_fp8", reinterpret_cast<const void*>(&window_block_c64_downsample_fp8)},
		{"window_block_c64_fp16", Resolve_window_block_c64_fp16()},
		{"window_block_c64_fp8", Resolve_window_block_c64_fp8()},
		{"window_block_c64_input_view_fp16", Resolve_window_block_c64_input_view_fp16()},
		{"window_block_c64_input_view_fp8", Resolve_window_block_c64_input_view_fp8()},
		{"window_block_c64_output_view_fp16", Resolve_window_block_c64_output_view_fp16()},
		{"window_block_c64_output_view_fp8", Resolve_window_block_c64_output_view_fp8()},
		{"window_block_c64_upsample_fp16", reinterpret_cast<const void*>(&window_block_c64_upsample_fp16)},
		{"window_block_c64_upsample_fp8", reinterpret_cast<const void*>(&window_block_c64_upsample_fp8)},
		{"window_ffn_c512_fp16", reinterpret_cast<const void*>(&window_ffn_c512_fp16)},
		{"window_ffn_c512_fp8", reinterpret_cast<const void*>(&window_ffn_c512_fp8)},
		{"window_ffn_input_view_c512_fp16", reinterpret_cast<const void*>(&window_ffn_input_view_c512_fp16)},
		{"window_ffn_input_view_c512_fp8", reinterpret_cast<const void*>(&window_ffn_input_view_c512_fp8)},
		{"window_ffn_projection_c512_fp16", Resolve_window_ffn_projection_c512_fp16()},
		{"window_ffn_projection_c512_fp8", Resolve_window_ffn_projection_c512_fp8()},
		{"window_ffn_projection_input_view_c512_fp16",
		 reinterpret_cast<const void*>(&window_ffn_projection_input_view_c512_fp16)},
		{"window_ffn_projection_input_view_c512_fp8",
		 reinterpret_cast<const void*>(&window_ffn_projection_input_view_c512_fp8)},
		{"window_qkv_c512_fp16", reinterpret_cast<const void*>(&window_qkv_c512_fp16)},
		{"window_qkv_c512_fp8", reinterpret_cast<const void*>(&window_qkv_c512_fp8)},
	}};
	return Table;
}
