// Grouped CUDA body emission only. Host dispatch lives in the shared C++ TU.
#include "kernel_impl/window_block_c256_downsample_fp8.cuh"
#include "kernel_impl/window_block_c256_downsample_fp16.cuh"
#include "kernel_impl/window_block_c256_input_view_fp8.cuh"
#include "kernel_impl/window_block_c256_input_view_fp16.cuh"
#include "kernel_impl/window_block_c256_fp16.cuh"
#include "kernel_impl/window_block_c256_fp8.cuh"
#include "kernel_impl/window_block_c256_output_view_fp8.cuh"
#include "kernel_impl/window_block_c256_output_view_fp16.cuh"
#include "kernel_impl/window_block_c256_upsample_fp8.cuh"
#include "kernel_impl/window_block_c256_upsample_fp16.cuh"
