// Grouped CUDA body emission only. Host dispatch lives in the shared C++ TU.
#include "kernel_impl/window_block_c128_downsample_fp16.cuh"
#include "kernel_impl/window_block_c128_downsample_fp8.cuh"
#include "kernel_impl/window_block_c128_input_view_fp8.cuh"
#include "kernel_impl/window_block_c128_input_view_fp16.cuh"
#include "kernel_impl/window_block_c128_fp16.cuh"
#include "kernel_impl/window_block_c128_fp8.cuh"
#include "kernel_impl/window_block_c128_output_view_fp8.cuh"
#include "kernel_impl/window_block_c128_output_view_fp16.cuh"
#include "kernel_impl/window_block_c128_upsample_fp16.cuh"
#include "kernel_impl/window_block_c128_upsample_fp8.cuh"
