"""Architecture-to-hardware orientation and prepared-plan tutorial."""
from common import code, svg, note, source_url

I = 'csrc/kernel_impl/shared/common/intrinsics.cuh'
W = 'csrc/kernel_impl/shared/common/warp_window32.cuh'

FOUNDATIONS = dict(slug='foundations', title='From a tensor to a warp',
summary='Read the architecture, then follow one physical tile through addresses, caches, fragments and numerical boundaries.', body=f"""
<h2 id="model">The model piece: one residual FFN → attention block</h2>
<p>The ordinary block is the recurring unit in this encoder–decoder. For one spatial token, the FFN mixes channels; attention then mixes positions. The block computes <code>Zraw = FFN(X) + ffn_scale ⊙ R</code>, publishes <code>Z</code>, projects it to Q/K/V, and finishes with <code>Yraw = projection(attend(Q,K,V)) + attn_scale ⊙ Rattn</code>. The first residual normally reads X; the second reads Zraw at C32 and published Z at larger widths. The <a href="architecture.html#follow-one-block">architecture guide</a> explains these choices before any GPU layout is introduced.</p>
<p>Here “token” means one spatial position and its channel vector. A head is a 32-channel slice used by attention. An 8×8 window contains 64 tokens; its four physical 4×4 tiles each contain 16 tokens. A CTA is one CUDA thread block; each warp contains 32 lanes. A lane owns fragments of several tokens, so <strong>one lane is not one token</strong>.</p>
<figure class="diagram"><img src="../figures/architecture/residual_block.svg" alt="Architecture: FFN residual, QKV normalization, attention and output residual" loading="lazy"><figcaption>The model graph from docs/ARCHITECTURE.md. The chapters below connect these logical tensors to concrete kernel storage.</figcaption></figure>
<h2 id="hierarchy">1. Separate logical tensors from physical storage</h2>
<p>Start with a tensor's meaning, shape and precision. Then ask whether it exists as a global allocation, a shared-memory tile, or only as distributed register fragments. A drawn score matrix is an algorithmic object; it does not prove a global allocation. C32 can keep the whole ordinary block inside a warp's register state, C512 exposes intermediate global buffers between four launches, and C1024 streams key tiles without allocating the complete score matrix.</p>
{svg('Storage and compute routes used in this repository', '0 0 1080 630', '''
<rect x="22" y="22" width="1036" height="98" rx="12" class="storage"/><text x="44" y="51" class="label">GPU global address space · backing VRAM (device DRAM)</text><text x="44" y="81" class="small">Packed input/output · weight records · skips · C512 intermediates · C1024 Half split scratch · counters</text><text x="44" y="104" class="small">A global address identifies bytes; it does not tell you whether the next access will hit in cache.</text>
<path d="M540 120 V148" class="edge"/><rect x="310" y="153" width="460" height="61" rx="9" class="storage"/><text x="334" y="178" class="label">L2 cache · shared across SMs</text><text x="334" y="201" class="small">Hardware-managed; cache residency is not measured here</text>
<path d="M380 214 V252" class="edge"/><rect x="54" y="257" width="406" height="75" rx="9" class="storage"/><text x="74" y="282" class="label">Per-SM L1 / texture caching</text><text x="74" y="306" class="small">__ldca permits L1; texture paths have their own access rules</text>
<path d="M697 214 V253" class="edge"/><rect x="564" y="257" width="462" height="75" rx="9" class="tensor"/><text x="584" y="282" class="label">CTA shared memory · programmer-managed SRAM</text><text x="584" y="306" class="small">cp.async / bulk-copy tiles; explicit offsets and barriers</text>
<path d="M775 179 H1038 V422 H930" class="edge"/><text x="900" y="361" class="small">__ldcg / .cg</text><text x="900" y="383" class="small">bypasses L1</text>
<path d="M257 332 V385" class="edge"/><path d="M795 332 V385" class="edge"/><rect x="65" y="390" width="865" height="75" rx="9" class="tensor"/><text x="85" y="417" class="label">Per-thread register operands · shared work across a warp</text><text x="85" y="444" class="small">A: 4×u32/lane · B: 2×u32/lane · C/D: 2×u32/lane (four Half accumulators)</text>
<path d="M335 465 V506" class="edge"/><path d="M698 506 V467" class="edge"/><rect x="238" y="511" width="562" height="70" rx="9" class="compute"/><text x="259" y="538" class="label">Warp-wide mma.sync → Tensor Core matrix operation</text><text x="259" y="563" class="small">FP8: m16n8k32 · FP16: m16n8k16 · results return to registers</text>
<text x="65" y="610" class="small">Publication: registers → global stores, or registers → shared → peer warp. No TMEM is used by these sources.</text>
''', 'Arrows distinguish ordinary cached loads, L1-bypassing loads and asynchronous shared-memory copies. The diagram describes routes, not fixed latency or guaranteed cache hits.')}
<p>Registers and shared memory are explicitly addressed or represented in the source. L1/L2 are caches along memory paths, not software tensor buffers. The wrappers use <code>__ldca</code> for some reusable data, <code>__ldcg</code> for streaming data, and <code>L1::no_allocate</code> for selected output/counter traffic. These are cache controls or hints, not synchronization. A register array can spill into CUDA local memory if compilation requires it; the prefix <code>r_</code> describes intended arithmetic payload, not a proof of zero spill traffic. Inspect compiled resource reports and profiling before making that claim.</p>
<p>These kernels execute <code>mma.sync</code> with register operands. Their Blackwell measurement target is SM120; do not substitute SM100 <code>tcgen05</code>, TMEM or warp-group MMA diagrams. Some copy intrinsics select newer operations at SM90+, while Ampere/Ada use a different copy implementation. The instruction wrappers show exactly where this choice is made.</p>
{code(I, 193, 227, 'The two exact MMA instructions and the global-store policy')}
<p>Hardware context: NVIDIA documents the register distribution and cache operators in the <a href="https://docs.nvidia.com/cuda/parallel-thread-execution/">PTX ISA reference</a>. The chapter-specific mappings are taken from this repository's loaders and consumers, not inferred solely from that generic reference.</p>
<h2 id="fragments">2. Decode the warp's accumulator ownership</h2>
<p>For an m16n8 operation, 32 lanes collectively produce 16×8 = 128 results. The four Half values held by each lane are stored in two 32-bit words. Let <code>g = lane // 4</code> and <code>q = lane % 4</code>. The low/high halves of word 0 represent row g and columns 2q, 2q+1. Word 1 represents row g+8 at those same columns. When the output spans more than eight channels, the kernel repeats this fragment for column tiles.</p>
{svg('One lane owns four elements of an m16n8 result', '0 0 1000 350', '''
<rect x="25" y="27" width="410" height="292" rx="10" class="tensor"/><text x="46" y="57" class="label">16 rows × 8 columns = 128 Half results</text>
<path d="M80 80 H384 M80 94 H384 M80 108 H384 M80 122 H384 M80 136 H384 M80 150 H384 M80 164 H384 M80 178 H384 M80 192 H384 M80 206 H384 M80 220 H384 M80 234 H384 M80 248 H384 M80 262 H384 M80 276 H384 M80 290 H384 M80 304 H384 M80 80 V304 M118 80 V304 M156 80 V304 M194 80 V304 M232 80 V304 M270 80 V304 M308 80 V304 M346 80 V304 M384 80 V304" stroke="#c5d8d4" fill="none"/>
<rect x="156" y="136" width="76" height="14" fill="#147d78"/><rect x="156" y="248" width="76" height="14" fill="#c06b36"/><text x="41" y="146" class="small">r4</text><text x="32" y="258" class="small">r12</text><text x="161" y="78" class="small">c2 c3</text>
<path d="M438 172 H475" class="edge"/><rect x="485" y="40" width="490" height="269" rx="10" class="storage"/><text x="508" y="73" class="label">Example: lane 17 → g=4, q=1</text><text x="508" y="113" class="small">word 0 = [ D(4,2), D(4,3) ] · packed Half2</text><text x="508" y="143" class="small">word 1 = [ D(12,2), D(12,3) ] · packed Half2</text><text x="508" y="190" class="small">For channel column tile j:</text><text x="508" y="220" class="label">channels = 8j + 2 and 8j + 3</text><text x="508" y="259" class="small">Across all 32 lanes, each output element has one owner.</text><text x="508" y="284" class="small">Highlighted cells show the two row pairs owned by lane 17.</text>
''', 'MMA row numbers belong to a fragment. In local windows those rows map to a physical 4×4 tile, not to 16 consecutive image rows.')}
{code(W, 10, 38, 'Source contract: row halves, channel pairs and precision profiles')}
<p>For a C32 result, a lane holds four column tiles × two Half2 words = 16 Half results for each physical tile. A full window has four such tiles. That is why arrays such as <code>r_Ffn[4]</code> and <code>r_Pair[4][2]</code> represent a real tensor decomposition rather than arbitrary compiler register numbers. To read any later diagram, first identify its row axis, channel-column tile, K reduction panel and lane pair.</p>
<h2 id="addressing">3. Work one physical C32 input address by hand</h2>
<p>In the ordinary C32 packed path, the field is tiled into 4×4 blocks. Let <code>tile = tile_y × (Width/4) + tile_x</code>. The global byte offset of one lane's 16-byte load is <code>tile × TileBytes + chunk × 512 + lane × 16</code>. FP8 stores 16×32 elements in 512 bytes and has one K32 chunk. FP16 stores the same tile in 1024 bytes as two 512-byte K16 chunks. Each chunk has 32 adjacent lane vectors.</p>
<p>For tile 5 and lane 17, the offset is <code>5×512 + 17×16 = 2832</code> in FP8. The FP16 chunk-0 offset is <code>5×1024 + 17×16 = 5392</code>; chunk 1 starts at <code>5904</code>. These are addresses of four packed u32 words, not BHWC channel addresses. A separate view loader has a different plane-major formula. Copying BHWC bytes into the ordinary packed buffer would give plausible addresses and incorrect tensors.</p>
{code('csrc/kernel_impl/shared_encoder_decoder_c32_c64_c128_c256_fused_window/fp8/window_block_compact_fp8.cu', 65, 85, 'Coalesced tile load: one uint4 per lane per reduction chunk')}
<div class="explorer" id="lane-explorer"><h3>Try a lane and precision</h3><p>This calculator implements the formula immediately above and the accumulator map, not an emulator of all kernel arithmetic.</p><div class="controls"><label>Lane <input id="lane-input" type="number" min="0" max="31" value="17"></label><label>Physical tile index <input id="tile-input" type="number" min="0" max="1023" value="5"></label><label>Precision <select id="precision-input"><option value="fp8">FP8 · K32</option><option value="fp16">FP16 · K16</option></select></label></div><output id="lane-result" aria-live="polite">FP8, tile 5, lane 17: byte offset 2832; output rows 4 and 12; channel pairs 2–3, 10–11, 18–19, 26–27.</output><svg id="lane-grid" viewBox="0 0 800 260" role="img" aria-label="Interactive 16 by 8 accumulator grid"></svg></div>
<h2 id="precision">4. Follow rounding as carefully as addresses</h2>
<p>“FP8 kernel” names the working publication/operand format, not every arithmetic instruction. In these bodies the E4M3 operands feed FP16-accumulating MMA. Half2 activation, residual arithmetic, reductions and some scratch buffers remain FP16. Some normalization steps widen to FP32 for approximate reciprocal or reciprocal square root, then round back to Half. Both precision paths therefore have explicitly ordered conversion boundaries.</p>
{svg('Precision publication is a numerical boundary', '0 0 1020 310', '''
<rect x="20" y="40" width="220" height="100" rx="10" class="tensor"/><text x="39" y="73" class="label">Half MMA accumulator</text><text x="39" y="101" class="small">raw values + scaled residual</text><text x="39" y="125" class="small">two Half values / u32 word</text>
<path d="M240 91 H290" class="edge"/><rect x="300" y="40" width="318" height="100" rx="10" class="compute"/><text x="321" y="73" class="label">FP8 publication</text><text x="321" y="101" class="small">cvt.rn.satfinite.e4m3x2.f16x2</text><text x="321" y="125" class="small">round two pairs; join four E4 bytes</text>
<path d="M618 91 H668" class="edge"/><rect x="679" y="40" width="316" height="100" rx="10" class="tensor"/><text x="700" y="73" class="label">Next MMA operand</text><text x="700" y="101" class="small">register / shared / global E4 payload</text><text x="700" y="125" class="small">same logical shape; different values</text>
<path d="M129 140 V207 H772" class="edge"/><text x="207" y="195" class="small">Raw residual or pooling branch may retain pre-publication Half values</text>
<text x="30" y="265" class="small">FP16 publication keeps Half payloads. FP16 record offsets are independently defined; do not double every FP8 offset.</text>
''', 'The kernel may preserve a raw Half value for one consumer while another reads its rounded FP8 publication. Fusing the two paths must preserve that distinction.')}
{code(I, 106, 125, 'Four Half values become four E4M3 bytes in one scoped conversion sequence')}
<p>Weight matrices are packed in reduction panels. A K32 FP8 panel and K16 FP16 panel each use 32 bytes per output column, which helps preserve 16-byte lane loads across precisions. But Half scales, biases, padding and matrix boundaries are not uniformly doubled. The source profiles are the contract. Likewise the model's activation is a recovered clamped polynomial and its attention exponential is a recovered surrogate. Replacing them with framework SiLU or stable softmax changes the computation.</p>
<h2 id="pipeline">5. Read an asynchronous-copy pipeline as a storage lifetime</h2>
<p>Large tiled kernels stage operands in shared memory. Distinguish <em>copy completion</em> from <em>consumer completion</em>: before reading a stage, its copy must have completed; before overwriting the stage, every consumer of the old tile must have finished. An mbarrier tracks the copy/arrival phase. CTA barriers or the explicit schedule coordinate stage reuse. A barrier variable by itself does not prove either invariant—trace the issuer, expected transaction count, arrivals, wait and next write.</p>
{svg('A conceptual two-stage operand pipeline', '0 0 1040 335', '''
<text x="27" y="32" class="label">Time →</text><text x="180" y="32" class="small">prefill</text><text x="409" y="32" class="small">consume tile 0</text><text x="650" y="32" class="small">consume tile 1</text><text x="872" y="32" class="small">continue</text>
<text x="22" y="101" class="label">stage 0</text><rect x="159" y="60" width="217" height="64" rx="8" class="storage"/><text x="174" y="88" class="small">global → shared tile 0</text><text x="174" y="109" class="small">wait until ready</text><rect x="393" y="60" width="217" height="64" rx="8" class="compute"/><text x="410" y="87" class="small">shared → registers → MMA</text><text x="410" y="109" class="small">last consumer finishes</text><rect x="627" y="60" width="217" height="64" rx="8" class="storage"/><text x="643" y="88" class="small">refill tile 2, same bytes</text><text x="643" y="109" class="small">only after safe recycling</text>
<text x="22" y="196" class="label">stage 1</text><rect x="393" y="155" width="217" height="64" rx="8" class="storage"/><text x="410" y="183" class="small">global → shared tile 1</text><text x="410" y="205" class="small">overlap if hardware permits</text><rect x="627" y="155" width="217" height="64" rx="8" class="compute"/><text x="643" y="183" class="small">wait → load → MMA</text><rect x="861" y="155" width="157" height="64" rx="8" class="storage"/><text x="875" y="183" class="small">refill tile 3</text>
<text x="26" y="269" class="label">Hazard checks</text><text x="205" y="269" class="small">Read only after copy completes. Refill only after old readers finish.</text><text x="26" y="304" class="small">This is an explanatory schedule; individual kernels use different stage counts, operand tiles and barrier offsets.</text>
''', 'Overlap is an optimization intent. Source inspection alone does not quantify the latency hidden by a particular pipeline.')}
{code(I, 236, 269, 'One API, two copy mechanisms: SM90+ bulk and SM80/89 lane-striped copies')}
<p>For a 512-byte transfer below SM90, lane l copies 16 bytes beginning at <code>16l</code>. For 1024 bytes it also copies at <code>16l+512</code>. All participating producers attach their own copies to the mbarrier. On SM90+, one elected lane issues a bulk transfer and the pipeline accounts for expected bytes. The fallback is cooperative parallel copying, not 32 copies serialized through one lane. Study the precise prefill/refill placement in the C512 and C1024 chapters next.</p>
<h2 id="reading">6. A repeatable method for reading every kernel</h2>
<ol><li>Find the model record and operation in the <a href="architecture.html">architecture</a>; write its logical shapes and precision boundaries.</li><li>Find the logical entry in the <a href="source-atlas.html">source atlas</a>; templates can give several public configurations one body.</li><li>Read the launch grid and map block, warp and lane axes to tokens, heads, output columns and reduction splits.</li><li>Annotate every address with its unit: element, Half pair, u32 word, uint4 vector or byte.</li><li>Trace one producer and one consumer through every register/shared/global publication.</li><li>Only then explain why fusion, reuse, tiling, conversion packing or launch ordering can reduce work. Keep measured results separate from the intended mechanism.</li></ol>
""")

RUNTIME = dict(slug='runtime', title='Launch plans, synchronization & optimization evidence', summary='How model records become physical launches, why dependent splits need capacity checks, and how to evaluate an optimization.', body=f"""
<h2 id="model">The model piece: the prepared-feature encoder–decoder trunk</h2>
<p>The prepared plan implements numbered records 1–69: five encoder levels, eight C1024 global blocks, the transition at record 39, and the returning decoder levels. The complete architecture has records 0–70, but the prepared-feature benchmark starts after input preprocessing and stops before output postprocessing. The <a href="frontend.html">frontend chapter</a> documents those separate entry points; the <a href="architecture.html#the-whole-network">architecture guide</a> shows the full model.</p>
<p>One numbered record is not necessarily one launch. A fused C32 block fits one kernel. An ordinary C512 block spans four. A C1024 block needs FFN expansion, contraction, QKV, attention and projection, with counter clearing and repacking at selected boundaries. Both current prepared plans assert 185 logical calls and 37 distinct entries (36 compute/repack plus counter clear). A capacity fallback can turn one dependent logical call into several physical launches.</p>
{svg('From the model graph to device work', '0 0 1060 400', '''
<rect x="20" y="32" width="270" height="103" rx="10" class="tensor"/><text x="39" y="65" class="label">Model records 1–69</text><text x="39" y="93" class="small">Geometry + packed weights</text><text x="39" y="117" class="small">Saved encoder skips stay live</text><path d="M290 83 H341" class="edge"/>
<rect x="351" y="32" width="302" height="103" rx="10" class="storage"/><text x="371" y="65" class="label">Prepared plan (CPU)</text><text x="371" y="93" class="small">185 logical calls, typed ABI bindings</text><text x="371" y="117" class="small">Addresses + extents + grids + records</text><path d="M653 83 H704" class="edge"/>
<rect x="714" y="32" width="324" height="103" rx="10" class="compute"/><text x="734" y="65" class="label">Resource admission</text><text x="734" y="93" class="small">Loaded binary, thread/shared limits</text><text x="734" y="117" class="small">Actual occupancy × available SMs</text>
<path d="M875 135 V178 H260 V219" class="edge"/><path d="M875 178 V219" class="edge"/>
<rect x="44" y="229" width="420" height="91" rx="10" class="tensor"/><text x="64" y="262" class="label">Full dependent grid fits capacity</text><text x="64" y="291" class="small">One grid; split scratch and device counters</text><rect x="585" y="229" width="440" height="91" rx="10" class="tensor"/><text x="605" y="262" class="label">Full dependent grid exceeds capacity</text><text x="605" y="291" class="small">Z=1 launches in stream order; no intra-grid wait</text><text x="44" y="365" class="small">Independent Z work is never split by this policy. The input's actual geometry remains unchanged.</text>
''', 'The launcher schedules the existing mathematical work. It does not replace the model or round inputs to a benchmark resolution.')}
<h2 id="prepare">1. Prepare storage before capture</h2>
<p>Python hands the C++ plan a contiguous raw-byte GPU input plus precision-specific packed records. C++ checks the selected CUDA device, exact physical extents, 16-byte alignment and disjoint input/weight ranges. It allocates workspaces, puts 256-byte guard spans around each, and builds typed parameter blocks and buffer bindings. The plan keeps tensor ownership so addresses remain valid during execution. Creating this state happens outside CUDA Graph capture; replay can then use already-stable addresses.</p>
{code('csrc/kernel_launcher/deployment.cpp', 49, 66, 'The raw physical-buffer contract')}
{code('csrc/kernel_launcher/deployment.cpp', 123, 146, 'Guarded allocations and logical-call census')}
<p>The <code>uint8</code> host tensor type is a storage container. It does not imply all contents are 8-bit arithmetic. FP16 activations, Half scratch, packed FP8 weights and int32 counters all live in byte-addressed allocations with distinct ABI meanings. Using an arbitrary contiguous PyTorch tensor without packing cannot satisfy the layout contract.</p>
<h2 id="padding">2. Distinguish four kinds of extent</h2>
<table><thead><tr><th>Extent</th><th>Purpose</th><th>4K example</th></tr></thead><tbody><tr><td>Valid image</td><td>The caller's requested field</td><td>3840×2160</td></tr><tr><td>Network spatial field</td><td>Geometry's padded levels, already part of the model's tokens</td><td>Full 3840×2176; bottleneck 60×36</td></tr><tr><td>Physical token allocation</td><td>C++ token buffers round T to a multiple of 32</td><td>T=2160 → 2176 rows</td></tr><tr><td>Attention traversal</td><td>Key loop processes 64-token tiles; missing keys are zero-filled</td><td>T=2160 → 2176 visited slots</td></tr></tbody></table>
<p>The last two agree at 4K but need not agree for other shapes. A tensor buffer allocated to a multiple of 32 does not authorize unconditional loads up to a multiple of 64. Kernels predicate their tail loads. Likewise a finite-value check should cover logical values, not assume every unused allocation byte has been initialized. The final attention denominator removes only extra traversal slots; it does not delete the spatial padding already included in T.</p>
{code('csrc/kernel_launcher/plan_geometry.h', 68, 104, 'Logical tokens, 32-row allocation padding and physical byte formulas')}
<h2 id="split">3. Follow a dependent split through its publication</h2>
<p>A large contraction can partition its reduction dimension over Z. Each split computes a partial result in Half, with an explicitly ordered update to scratch. A later split must not consume scratch before the earlier producer has published it. The resident path uses global counters with the initial sentinel −1, release stores and polling reads. A CTA barrier coordinates participating threads after polling. Read the particular kernel for the expected counter value and final publication: the protocols differ, and attention's “ready” counter is not automatically a QKV split number.</p>
{code('csrc/kernel_impl/shared/common/completion_counter_clear.cu', 5, 12, 'Reset live counters to the not-ready sentinel')}
{code(I, 47, 73, 'Counter wrappers: relaxed read, acquire helper and release publication')}
{note('The presence of <code>AcquireSplitPublication()</code> in the shared header does not mean every kernel calls it. For example, the decoder and some bottleneck bodies at this snapshot poll relaxed counters without that helper. These pages describe the source protocol; they do not claim a new formal memory-order proof or fresh hardware qualification.')}
<p>A release store expresses publication order; a consumer must separately establish the required visibility. Cache selection alone is not an acquire operation. For ordered launches, completion and ordering on the same CUDA stream establish an inter-kernel boundary before the next split reads scratch. This is a different mechanism from spinning inside a single grid.</p>
<h2 id="capacity">4. Avoid scheduling-dependent progress</h2>
<p>Ordinary CUDA scheduling does not promise that a predecessor block runs before a block that spins on it. If waiters occupy all SM capacity while their producers have not been scheduled, a dependent full grid can fail to progress. The policy therefore compares the complete logical grid, not only one XY plane, against the number of simultaneously active blocks reported for the loaded function. With P=grid.x×grid.y, S=grid.z and capacity C=active_blocks_per_SM×SM_count, one grid is selected only when <code>P ≤ floor(C/S)</code>. This division form avoids multiplication overflow.</p>
{code('csrc/kernel_launcher/split_launch_policy.h', 4, 22, 'Admission uses the entire dependent grid')}
<p>Worked example: P=96 blocks per XY plane, S=4 splits and capacity C=264 gives <code>96 &gt; 264/4 = 66</code>, so the runtime issues four ordered Z=1 launches. Each 96-block plane can run in as many waves as needed. With P=48, the entire 192-block grid fits that capacity; the resident route remains available. These numbers illustrate the policy; they are not measured device resources.</p>
{svg('Four dependent splits scheduled as ordered launches', '0 0 1040 360', '''
<text x="25" y="32" class="label">One CUDA stream: split 0 completes before split 1 starts</text>
<rect x="24" y="70" width="218" height="96" rx="10" class="compute"/><text x="42" y="101" class="label">Z=1 · OrderedSplit=1</text><text x="42" y="127" class="small">compute split 0; write Half</text><text x="42" y="149" class="small">scratch; no predecessor wait</text><path d="M242 117 H267" class="edge"/>
<rect x="275" y="70" width="218" height="96" rx="10" class="compute"/><text x="291" y="101" class="label">Z=1 · OrderedSplit=2</text><text x="291" y="127" class="small">read/update same Half scratch</text><text x="291" y="149" class="small">preserve split rounding</text><path d="M493 117 H518" class="edge"/>
<rect x="527" y="70" width="218" height="96" rx="10" class="compute"/><text x="543" y="101" class="label">Z=1 · OrderedSplit=3</text><text x="543" y="127" class="small">next ordered partial sum</text><text x="543" y="149" class="small">same global scratch addresses</text><path d="M745 117 H770" class="edge"/>
<rect x="779" y="70" width="235" height="96" rx="10" class="compute"/><text x="795" y="101" class="label">Z=1 · OrderedSplit=4</text><text x="795" y="127" class="small">final sum + epilogue</text><text x="795" y="149" class="small">publish output precision</text>
<path d="M133 166 V216 M384 166 V216 M636 166 V216 M897 166 V216" stroke="#576c83"/><rect x="24" y="216" width="990" height="68" rx="10" class="storage"/><text x="46" y="246" class="label">Global scratch persists across launches; each launch's registers and shared memory are new</text><text x="46" y="270" class="small">Control value 0 selects resident-grid mode; positive values encode logical split index + 1.</text><text x="26" y="331" class="small">The fallback is recorded inside CUDA Graph capture too. More launches can cost time but remove the over-capacity wait.</text>
''', 'The diagram illustrates the split-K4 family. QKV uses its own split count. The same host policy applies to dependent split entries only.')}
{code('csrc/kernel_launcher/split_launch.cpp', 41, 66, 'How one logical call becomes stream-ordered split launches')}
<h2 id="portability">5. Choose instructions and resources for the loaded device</h2>
<p>The host admits FP16 at SM80+ and FP8 at SM89+. It checks both the loaded binary and its virtual target: compiling a body to a trapping FP8 fallback and later JITing it for a newer GPU does not create a valid FP8 implementation. Block dimensions, static shared bytes and actual occupancy also gate admission. The README's physical measurements are on RTX PRO 6000 Blackwell, SM120; compilation for Ampere/Ada and execution of lower-target code on SM120 are different evidence from running on actual SM80/89 hardware.</p>
{code('csrc/kernel_launcher/architecture_support.h', 15, 19, 'The precision floor')}
{code('csrc/kernel_launcher/architecture_support.h', 55, 66, 'Shared-memory and active-block checks')}
<p>Resolution policy transfers a configuration, not a performance guarantee. The generated selector keeps actual input dimensions, independently records exact-shape admission and measured coverage, and can choose a nearest measured configuration within a GPU/precision family. A transferred configuration must never be described as a new benchmark result.</p>
<h2 id="optimization">6. Connect each optimization to the work it saves</h2>
<table><thead><tr><th>Source design</th><th>Intended reduction</th><th>What can offset the gain</th><th>Evidence to collect</th></tr></thead><tbody>
<tr><td>Fuse a local FFN, QKV and attention</td><td>Intermediate global writes/reads and launches</td><td>Longer register lifetimes; spills; fewer active blocks</td><td>Compiled resources, local traffic, full-trunk timing</td></tr>
<tr><td>Keep weights/fragments in registers</td><td>Reloads and layout conversion</td><td>Register pressure and instruction scheduling</td><td>SASS, register count, stall samples</td></tr>
<tr><td>Pack conversion and word join in one PTX scope</td><td>Redundant packing/permutation instructions</td><td>Compiler backend may already combine them</td><td>Compare actual emitted instructions</td></tr>
<tr><td>Use paired attention normalization at selected widths</td><td>Repeated shuffles and reciprocal work</td><td>More live state and selection work</td><td>Kernel and balanced graph timing</td></tr>
<tr><td>Fuse a producer's output view or consumer's input view</td><td>A separate layout staging pass</td><td>Address arithmetic, less favorable coalescing</td><td>Address correctness and total memory traffic</td></tr>
<tr><td>Prefetch shared tiles while computing</td><td>Exposed operand load latency</td><td>Extra shared capacity and synchronization</td><td>Pipeline stalls and active occupancy</td></tr>
<tr><td>Use a register cap</td><td>Can change allocation/scheduling</td><td>Spills; no automatic occupancy increase</td><td>Resources plus measured workload</td></tr></tbody></table>
<p>The repository's historical lessons report cases where reducing source complexity did not reduce instructions, where extra issued work was NOPs rather than additional tensor operations, and where an assembler backend changed scheduling. Those are reasons to measure the compiled workload, not promises that applying the same edit elsewhere will be faster. The tutorials explain mechanisms found in current source. They do not claim newly measured speedups.</p>
<h2 id="validation">7. Reproduce the relevant evidence</h2>
<p>First preserve the input shape, device, precision, source revision, toolkit/assembler, packed-record identity and timing scope. Check numerical outputs and intermediate boundaries at the intended precisions. For layout edits, validate reads/writes and boundary padding; for publication edits, preserve rounding and operand order; for scheduling edits, exercise both resident and ordered paths. Only then compare paired timings with both execution orders and matching warmup/capture rules.</p>
<p><a href="../SETUP.md">SETUP.md</a> explains build and deployment entry points. <code>python test_speed.py --per-kernel</code> provides local end-to-end speed measurement plus a separate diagnostic breakdown. The published README timings cover prepared-feature blocks 1–69 and exclude frontend/DLL processing. This documentation change does not rerun or requalify those GPU results.</p>
<p>To maintain this guide, run <code>python tools/build_kernel_docs.py</code> and <code>python tools/validate_kernel_docs.py</code>. Source excerpts are extracted from real files, have line numbers and pinned links, and are hashed into the generated manifest. The build checks that kernel/model sources still match the documented snapshot; updating the source requires an explicit documentation review and revision update.</p>
""")

CHAPTERS = [FOUNDATIONS, RUNTIME]
