"""Six independent frontend lessons; the fused core is inlined in each."""
from common import ROOT, code, svg, note
from lesson_support import pseudo, mma_primer, storage_legend

BASE='csrc/kernel_impl/shared_input_output_c32/common/'


def excerpt(path, first, last, caption):
    lines=(ROOT/path).read_text(encoding='utf-8').splitlines()
    a=next(i for i,l in enumerate(lines) if first in l)
    b=next(i for i,l in enumerate(lines[a:],a) if last in l)
    return code(path,a+1,b+1,caption)


def history_filter():
    body='''<h2 id="history-filter">Reconstruct history with five filtered samples</h2><p>The frontend uses a custom cross-shaped cubic reconstruction. Work in pixel-center coordinates. On either axis, set <code>center=floor(position−0.5)+0.5</code> and clamp <code>f=position−center</code> to [0,1]. The four one-dimensional weights are <code>l=−0.5(f+f³)+f²</code>, <code>ml=1+1.5f³−2.5f²</code>, <code>r=0.5(f³−f²)</code>, and <code>mr=1−l−ml−r</code>. The middle pair becomes one filtered sample with weight <code>m=ml+mr</code> at <code>center+mr/m</code>. The outer sample positions are <code>center−1</code> and <code>center+2</code>. Clamp all three positions, including the merged middle position, to the valid pixel-center interval [0.5,Extent−0.5].</p><p>Apply that construction on x and y. Sample only left, top, center, bottom and right, at products of the corresponding axis weights; omit the four corner products. Divide by the sum of the five retained weights. The source begins its accumulator with the top contribution, then adds left, center, bottom and right with explicit floating-point FMAs. This order and the approximate reciprocal are part of the reproduced arithmetic. A generic 16-tap bicubic filter does not implement this contract.</p>'''
    body+=svg('Five-tap history reconstruction','0 0 820 340','''<rect class="tensor" x="305" y="15" width="210" height="70" rx="7"/><text class="label" x="328" y="44">Top</text><text class="small" x="328" y="68">x.middle × y.left</text><rect class="tensor" x="35" y="116" width="220" height="70" rx="7"/><text class="label" x="52" y="145">Left</text><text class="small" x="52" y="169">x.left × y.middle</text><rect class="compute" x="305" y="116" width="210" height="70" rx="7"/><text class="label" x="322" y="145">Center</text><text class="small" x="322" y="169">x.middle × y.middle</text><rect class="tensor" x="565" y="116" width="220" height="70" rx="7"/><text class="label" x="582" y="145">Right</text><text class="small" x="582" y="169">x.right × y.middle</text><rect class="tensor" x="305" y="217" width="210" height="70" rx="7"/><text class="label" x="322" y="246">Bottom</text><text class="small" x="322" y="270">x.middle × y.right</text><path class="edge" d="M410 88 V109"/><path class="edge" d="M260 151 H298"/><path class="edge" d="M560 151 H522"/><path class="edge" d="M410 212 V193"/><text class="small" x="22" y="321">Each box is a texture sample; normalize the weighted RGB sum by the retained weight sum.</text>''')
    body+=code(BASE+'frontend_math.cuh',95,141,'Build one cubic axis')
    body+=code(BASE+'frontend_math.cuh',143,194,'Gather and normalize the five history samples')
    return body


def prelude(fp8,output=False,down=False):
    p='FP8 E4M3' if fp8 else 'FP16'
    body=f'''<h2 id="model">The model piece: {'record 70, decoder merge through the image head' if output else 'record 0, renderer features through the first C32 window block'}</h2><p>{'The decoder supplies a half-resolution 32-channel field and a full-resolution 32-channel skip saved by the frontend. This kernel performs nearest-neighbor expansion, a learned per-channel merge, one fused C32 FFN/attention block, a four-channel image head, and optional temporal display composition.' if output else 'This kernel turns renderer images and scalar controls into 16 Half features per pixel, applies a learned 16→32 adapter, and executes a complete local C32 FFN/attention block. It publishes the full-resolution feature field used as a skip later in the network.'} {'It also averages each raw Half 2×2 output cell into a half-resolution C32 field for the encoder. This pooling does not expand the channel count.' if down else ''} This document covers the <strong>{p}</strong> public entry from its inputs to its final stores.</p><p>Each block owns an 8×8 window, or 64 tokens. Four 4×4 physical tiles supply 16-token matrix fragments. The prepared launcher uses one warp, <code>block=(32,1,1)</code>, so the 32 CUDA lanes collectively own each matrix tile. All lanes must participate in shuffles and matrix instructions. Spatial predicates control boundary loads and stores without allowing a lane to exit before collective work. {'The grid accounts for OriginX/OriginY, which may be 0 or −4.' if output else 'The grid is (FullWidth/8,FullHeight/8).'} The physical image dimensions are multiples of eight; the valid renderer extent can be smaller.</p><p>The architecture's transformer sub-block is <code>32→128→32</code> FFN, followed by one 32-channel attention head over the 64-token window. Its optimized numerical operations include explicit Half rounding and a recovered attention-weight approximation. We will define them locally below. {'The final learned head uses Half matrix multiplication even in this FP8 entry.' if output else 'The input adapter uses Half matrix multiplication even in this FP8 entry.' if fp8 else 'The adapter, fused matrix operations and head operands use Half on this path.'} The <a href="architecture.html">architecture companion</a> provides the broader encoder–decoder map.</p>'''
    nodes=[('Low C32 + skip','global packed arrays'),('Half merge','expand + scale + add'),('Fused C32 block','FFN → local attention'),('Head + display','Half → float surface')] if output else [('Renderer images','texture samples + controls'),('16 Half features','shared [2][64] uint4'),('16 → 32 adapter','Half tensor-core MMA'),('Fused C32 block','FFN → local attention')]
    inner=''
    for i,(title,sub) in enumerate(nodes):
        x=15+230*i
        inner+=f'<rect class="{["tensor","storage","compute","tensor"][i]}" x="{x}" y="30" width="215" height="110" rx="8"/><text class="label" x="{x+12}" y="66">{title}</text><text class="small" x="{x+12}" y="103">{sub}</text>'
        if i<3:inner+=f'<path class="edge" d="M{x+215} 86 H{x+228}"/>'
    body+=svg('Frontend model stages','0 0 930 180',inner,'Each intermediate is introduced below where it is first produced. The fused C32 block is explained in full on this page.')
    body+='''<h2 id="baseline">Build a scalar oracle for one window</h2><p>Separate correctness from layout initially. Represent a window as <code>[64,channels]</code>, implement the feature or merge operation, then the linear maps, activation, Q/K normalization, attention weights, weighted values and residuals. Preserve every publication boundary and Half arithmetic order. Once that oracle agrees for one window, replace one stage at a time with the packed implementation. A standard library FFN or softmax is useful as a conceptual sketch but cannot be the final bit-level oracle for these recovered formulas.</p>'''
    body+=pseudo(('''low = nearest_expand_2x(decode(low_planes))
raw = half_fma(decode(skip), adapter_scale, half_mul(low, input_scale))
ffn = half_linear_contract(publish(activation(half_linear_expand(publish(raw)))),
                           seed=half_mul(raw, ffn_scale))
q,k,v = project_and_normalize(publish(ffn))
attended = weighted_values(recovered_attention(q,k,bias),v)
raw_output = half_linear_output(publish(attended), seed=half_mul(ffn,attention_scale))
head4 = half_matmul(raw_output, half_head_weights)
surface = compose_color_and_optional_history(head4)''' if output else '''features = renderer_features_for_64_pixels()      # round to Half
raw_adapter = half_matmul(features, half_adapter_weights)
ffn = half_linear_contract(publish(activation(half_linear_expand(publish(raw_adapter)))),
                           seed=half_mul(raw_adapter, ffn_scale))
q,k,v = project_and_normalize(publish(ffn))
attended = weighted_values(recovered_attention(q,k,bias),v)
raw_output = half_linear_output(publish(attended), seed=half_mul(ffn,attention_scale))
full_resolution = publish(raw_output)''' + ('\npooled = publish(rounded_half_average_each_2x2(raw_output))' if down else '')), 'End-to-end logical reference')
    body+=f'''<p>Here <code>publish</code> means {'round and pack Half results into E4M3 operand bytes' if fp8 else 'rearrange Half accumulator pairs into the next instruction’s Half operand layout'}. It does not necessarily mean a global-memory write. The raw adapter/merge and raw FFN residual remain available as Half register fragments even when a published copy is consumed by the next matrix instruction.</p>
<h2 id="storage">Define storage and the 16-token instruction</h2>'''+storage_legend()+mma_primer(fp8)
    if fp8:
        body+='<p>The fixed Half adapter/head uses the following second fragment map. In an FP8 frontend there are therefore two different reduction widths in the same launch: K32 in the learned C32 block, K16 in the fixed Half boundary matrix.</p>'+mma_primer(False)
    return body


def preprocess(name,entry):
    fp8=name.endswith('fp8');down='downsample' in name;p='FP8' if fp8 else 'FP16'
    path='csrc/'+entry['header'];body=prelude(fp8,down=down)
    body+='''<h2 id="features">Sample a pixel and assemble its 16 feature channels</h2><p>Lane L visits local pixels <code>s=L</code> and <code>s=L+32</code>. Pixel coordinates are <code>x=8×block.x+(s%8)</code> and <code>y=8×block.y+s//8</code>. Outside the valid renderer extent, reflect once: <code>x′=2×ValidWidth−x−2</code>, similarly for y. The launcher ensures that one reflection is sufficient. Use reflected coordinates for images but original x/y for the noise hash, so two padded positions that sample the same image texel can still have different noise features.</p><p>Normalized image coordinates are <code>((x′+0.5)/ValidWidth,(y′+0.5)/ValidHeight)</code>. Each texture's transform computes <code>NormalizeX×fma(ScaleX,u,BiasX)</code>, likewise y. A texture handle is an opaque CUDA texture object, not a byte address you can dereference. The launcher backs it with a float32 HWC4 CUDA array, configures point or linear filtering as requested, and copies the tensor into that array before launch.</p><p>The color path explicitly rounds: <code>Half(texture)</code>, then a Half subtraction of 0.5, then a Half multiplication by <code>Half(ColorScale+ColorScale)</code>. A float affine expression followed by one Half conversion loses intermediate rounding points. History initially equals current color. Only when both history and motion handles exist does the kernel reconstruct a separate history value.</p>'''
    body+=code(path,15,40,'Pixel ownership, reflection and color conditioning')
    body+='''<p>With optional depth, visit the center followed by top-left, top-right, bottom-left and bottom-right samples. The prefer-greater flag selects the comparison direction. Equal or unordered candidates retain the previous winner, so visit order matters. Convert the winning depth offset to the motion texture's coordinate scale; sample motion there; then compute the previous UV with <code>fma(motion,MotionScale,uv)</code>. Reconstruct history with the five-tap filter explained next.</p>'''
    body+=code(path,41,95,'Depth-guided motion selection and history sampling')
    body+=history_filter()
    body+='''<h2 id="noise">Generate deterministic noise and conditioning features</h2><p>Noise is computed independently for each original integer pixel position and frame seed. All hash arithmetic is unsigned 32-bit with wraparound. The permutation first shifts its state right by <code>(state&gt;&gt;28)+4</code>, XORs it with the original state, and multiplies by 277803737. The initial state combines x, y and seed with three fixed multipliers and an XOR constant. After the first permutation, compute <code>pixelHash=(hash&gt;&gt;22) XOR hash</code>. Four stream-specific multiply/add pairs applied to pixelHash then feed the same permutation.</p><p>For each stream, form <code>u=(((hash&gt;&gt;30) XOR (hash&gt;&gt;8))+1)×2⁻²⁴</code>. The added one avoids log(0). Two Box–Muller pairs compute radii from approximate log2 and square-root instructions, and angles from the second uniform times 2π. Keep radius₀cos(angle₀), radius₀sin(angle₀), and radius₁cos(angle₁). A library random-number generator cannot reproduce this address-derived sequence.</p>'''
    body+=code(BASE+'input_features.cuh',36,84,'Hash, uniforms, and three Gaussian coordinates')
    body+='''<p>Conditioning channels retain their source names because the recovered instructions do not identify their renderer-level meanings. Start with the Green/Blue scalar controls. A conditioning texture multiplies them by its green and blue samples. The override flag initializes two extra channels to −1 rather than 0. With the flag set and no conditioning texture, an explicit nonnegative override selects the override branch: Blue becomes 1, and each negative override falls back to the original ConditioningBlue value. Preserve this branch structure; replacing it with a generic clamp changes its sentinel behavior.</p>'''
    body+=code(path,97,142,'Conditioning branches and the exact feature channel order')
    body+='''<div class="table-scroll"><table><thead><tr><th>Channels</th><th>Values before Half storage</th></tr></thead><tbody><tr><td>0,1,2,3</td><td>Noise x, noise y, noise z, constant 1</td></tr><tr><td>4,5,6,7</td><td>Conditioned current R,G,B; conditioned history R</td></tr><tr><td>8,9,10,11</td><td>History G,B; ConstantConditioning; Green</td></tr><tr><td>12,13,14,15</td><td>Blue; override Green; override Blue; constant 0</td></tr></tbody></table></div>
<h2 id="adapter">Stage the features once, then feed the Half adapter</h2><p>The shared allocation is <code>uint4 s_Plane[2][64]</code>: 2 planes × 64 pixels × 16 bytes = 2048 bytes. Plane 0 contains channels 0…7, plane 1 channels 8…15. Each thread writes one uint4 per plane for each of its two pixels. A block barrier finishes all producers before the warp gathers differently owned pixels into matrix operands. This is the only explicit shared feature staging; the subsequent C32 core keeps its working fragments in registers.</p><p>For tile <code>j=0…3</code> and A word <code>i=0…3</code>, read pixel <code>4(j%2)+32(j//2)+((L//4)%4)+8(L//16)+16(i%2)</code>, plane <code>i//2</code>, uint32 component <code>L%4</code>. Its shared byte address is <code>16×(64×plane+pixel)+4×component</code>. This gather transforms a pixel-major feature plane into the fixed MMA lane map.</p><p>For lane 13, tile 0, word 0, the pixel is 3 and component is 1: shared byte 52 holds feature channels 2 and 3 for pixel (3,0). Word 1 reads pixel 19 at byte 308, the same channel pair two image rows lower. Word 2 switches to plane 1, pixel 3, byte 1076, giving channels 10 and 11. This is exactly the two-row, two-reduction-half structure of m16n8k16.</p>'''
    body+=svg('Feature plane to adapter fragment','0 0 930 290','''<rect class="storage" x="15" y="30" width="300" height="190" rx="8"/><text class="label" x="32" y="61">Shared: 2 × 64 × uint4</text><text class="small" x="32" y="98">plane 0: channels 0…7</text><text class="small" x="32" y="128">plane 1: channels 8…15</text><text class="small" x="32" y="160">pixel s: row-major in 8×8</text><text class="small" x="32" y="190">barrier before operand gathers</text><path class="edge" d="M320 120 H377"/><rect class="tensor" x="387" y="48" width="235" height="152" rx="8"/><text class="label" x="402" y="79">Lane 13, tile 0</text><text class="small" x="402" y="113">A0 = pixel 3, c2/c3</text><text class="small" x="402" y="143">A1 = pixel 19, c2/c3</text><text class="small" x="402" y="173">A2/A3 = c10/c11</text><path class="edge" d="M627 120 H672"/><rect class="compute" x="682" y="48" width="230" height="152" rx="8"/><text class="label" x="697" y="79">16 → 32 Half</text><text class="small" x="697" y="113">four N8 instructions</text><text class="small" x="697" y="143">raw adapter in registers</text><text class="small" x="697" y="173">four 16-token tiles</text><text class="small" x="20" y="264">Global Half weights → cached loads → B registers; shared features → A registers → Half accumulators.</text>''')
    body+=code(path,145,186,'Feature barrier, adapter weight loads and Half matrix instructions')
    body+=f'''<p>The adapter matrix occupies 1024 bytes (16×32×2). Each lane loads two uint4 vectors at <code>AdapterOffset + pair×512 + L×16</code>. Each vector supplies B words for two output groups. Four N8 matrix instructions produce 32 output channels per 16-token tile, seeded with zero. The profile inserts this fixed Half matrix at the ordinary C32 FFN-scale offset, shifting every following scale/bias/projection field by 1024 bytes. Use this frontend profile; ordinary window offsets would read the wrong weights. The complete packed record is {21696 if fp8 else 33984} bytes on this path.</p>'''
    body+=code(BASE+'frontend_profiles.cuh',6,19,'Frontend-specific packed-weight offsets')
    from lessons_windows import c32_core_lesson
    body+=c32_core_lesson(fp8,'the raw Half adapter result r_Adapter',path)
    body+='''<h2 id="publication">Publish the full-resolution feature field</h2><p>For each physical 4×4 tile, pack the output fragment into the selected operand precision. The byte address for lane L and reduction chunk k is <code>tileLinear×TileBytes+k×512+L×16</code>, where <code>tileLinear=tileY×(FullWidth/4)+tileX</code>. The lane emits one uint4 vector at each such address. A complete warp writes 512 bytes per chunk. TileBytes is 512 for FP8 and 1024 for FP16. The four tile positions cover the 8×8 window exactly once.</p><p>The store helper uses the source's no-allocation cache policy. This affects cache handling, not the output layout or synchronization contract. A later stream-ordered launch consumes the global buffer. No intermediate FFN, QKV, 64×64 score matrix or expanded hidden tensor has been written to global memory along the fused path.</p>'''
    body+=excerpt(path,'const int64_t g_TileIndex','r_Output.r_Word[2]', 'Full-resolution tile address and packed publication') if 'const int64_t g_TileIndex' in (ROOT/path).read_text() else excerpt(path,'const int g_TileColumns = WindowParameters.Width / 4','r_Output.r_Word[2]','Full-resolution tile address and packed publication')
    if down:
        body+='''<h2 id="pool">Pool the raw Half result before precision publication</h2><p>Retain four raw output tiles in <code>r_Output[4]</code>. For each output channel pair, the pooling helper routes adjacent tiles and row halves into a common lane pattern. Swapping lane bits 2 and 3 changes a four-wide token arrangement into two-wide pooled cells; XOR 4 selects the horizontal neighbor and XOR 16 the vertical neighbor. Four shuffles gather top-left, top-right, bottom-left and bottom-right Half pairs.</p><p>The arithmetic tree is <code>HalfMul(HalfAdd(HalfAdd(TL,TR),HalfAdd(BL,BR)),0.25)</code>. Three rounded Half additions precede the rounded quarter multiplication. Pooling FP32 values, or decoding an already-published FP8 feature image and averaging that, would change the result. This second output has shape <code>[FullHeight/2,FullWidth/2,32]</code>, not 64 channels.</p>'''
        body+=code('csrc/kernel_impl/shared/common/window_pool.cuh',6,59,'Lane routing and the exact Half pooling tree')
        body+=svg('Pool raw output, publish two different views','0 0 920 235','''<rect class="tensor" x="15" y="50" width="260" height="125" rx="8"/><text class="label" x="30" y="82">Raw Half: 8×8×32</text><text class="small" x="30" y="115">four register tiles</text><text class="small" x="30" y="145">before FP8/Half publication</text><path class="edge" d="M280 83 H390 V50 H445"/><path class="edge" d="M280 145 H390 V170 H445"/><rect class="storage" x="455" y="15" width="440" height="75" rx="8"/><text class="label" x="470" y="44">Full-resolution skip → native 4×4 tile storage</text><text class="small" x="470" y="72">pack directly from the raw Half result</text><rect class="compute" x="455" y="130" width="440" height="75" rx="8"/><text class="label" x="470" y="159">Rounded 2×2 average → 4×4×32 channel planes</text><text class="small" x="470" y="187">pack only after the three Half adds and quarter multiply</text>''')
        body+=f'''<p>The pooled buffer is channel-plane storage. Let chunk k range over {1 if fp8 else 2} operand chunks and word i over 0…3. Then <code>x=4×block.x+(L//4)%4</code>, <code>y=4×block.y+L//16+2(i%2)</code>, <code>plane=2k+i//2</code>, and byte address is <code>16×((plane×PooledHeight+y)×PooledWidth+x)+4(L%4)</code>. Each plane holds {'16 E4M3 channels' if fp8 else '8 Half channels'} per pixel. The compact C32 extent is exactly half of the full extent; the wider kernels' extra aligned-padding clear is not invoked here.</p>'''
        body+=code('csrc/kernel_impl/encoder_c32_c64_c128_c256_downsample/common/window_downsample.cuh',17,54,'Publish compact C32 pooled channel planes')
    body+='''<h2 id="rebuild">Reconstruct the final frontend in working stages</h2><ol><li>Implement coordinate reflection, texture transforms, exact Half color conditioning, noise and conditioning channel construction. Inspect all 16 values for one known pixel.</li><li>Write those values into the two shared planes. Add the block barrier and verify every adapter A word against the lane map before enabling matrix multiplication.</li><li>Load the fixed Half adapter weights using the frontend offsets. Execute four output groups per tile and retain the raw Half result.</li><li>Implement the complete fused core above, preserving raw residuals, panel order, normalization, recovered attention weights and publication boundaries.</li><li>Implement full-resolution vector stores. For this entry's optional pooling path, derive the second output from raw Half registers and apply its distinct channel-plane address formula.</li></ol><p>The fusion removes global round trips and launches for the adapter and transformer stages. The shared feature buffer solves a real layout mismatch between per-pixel texture work and tensor-core row ownership. Register retention and unrolled panel loops trade local storage pressure for reuse. The source specifies <code>__maxnreg__(168)</code>; this is a compiler limit, not evidence that exactly 168 registers are allocated or that no spilling occurs.</p>
<h2 id="tests">Test each boundary before testing a full frame</h2><ol><li>Use an 8×8 image with coordinate-coded colors and zero or fixed motion. Verify feature channel order, reflection at smaller valid extents, and deterministic noise for the same seed.</li><li>Test optional handles independently, including history without motion, conditioning texture versus explicit overrides, and equal-depth candidates. Check the required fallback branches.</li><li>Use sparse adapter and transformer weights to isolate one input feature and one output channel. Compare unpacked register-fragment coordinates with the scalar oracle.</li><li>For FP8, compare the raw Half residual with its E4M3-published copy separately. Deliberately choose values that round differently to detect accidental residual quantization.</li><li>For the pooling entry, use a 2×2 cell whose Half reduction differs from FP32 averaging. Check both the full-resolution native layout and pooled channel-plane layout, with canaries beyond each allocation.</li></ol><p>These are reconstruction checks to run on the target GPU; the documentation itself adds no new benchmark or correctness qualification.</p>'''
    body+='''<p>Two fixtures have explicit expected values. With constant current RGB=0.5, ColorScale=1, and either history or motion absent, feature channels 4…9 are exactly Half zero, channel 3 is Half one, and channel 15 is Half zero. With every learned matrix and attention bias set to zero, all scales set to one, and finite conditioning values small enough to remain finite in Half, the adapter and all final feature outputs are zero regardless of the finite noise features; for the pooling entry its C32 low field is also zero. These checks expose feature ordering and publication errors before random comparisons.</p>'''
    return dict(name=name,title=f'{p} input frontend'+(' with pooling' if down else '')+': pixels to the first window block',summary='Build renderer features, derive shared-to-MMA addressing, execute the complete fused transformer, and publish the exact native output layouts.',family='Input frontend',body=body)


def postprocess(name,entry):
    fp8=name.endswith('fp8');p='FP8' if fp8 else 'FP16';path='csrc/'+entry['header'];body=prelude(fp8,output=True)
    body+='''<h2 id="merge">Load the low field, expand pixels, and merge the skip</h2><p>The low field is channel-plane storage at <code>lowH=Height/2</code>, <code>lowW=Width/2</code>. An 8×8 output window starts at <code>ox=8×block.x+OriginX</code>, <code>oy=8×block.y+OriginY</code>. Lane L loads <code>x=ox/2+(L//4)%4</code> and <code>y=oy/2+L//16+2r</code> for rows r=0,1. Plane p is at byte offset <code>16×((p×lowH+y)×lowW+x)+4(L%4)</code>. Invalid coordinates load zero; a singleton dimension uses coordinate zero for its broadcast case.</p>'''
    body+=f'''<p>This path has {'two planes, each storing 16 E4M3 channels per pixel. A uint32 load holds four E4 bytes; decode its lower and upper 16-bit halves into two Half pairs. The four resulting Half channel-pair groups share the same later merge schedule.' if fp8 else 'four planes, each storing eight Half channels per pixel. Each uint32 load already holds the Half pair needed by the merge.'} The full-resolution skip uses the native 4×4 tile layout, loaded as uint4 vectors at <code>tileLinear×{512 if fp8 else 1024}+chunk×512+L×16</code>. {'Decode its packed E4 pairs before the Half merge.' if fp8 else 'Select the appropriate Half word directly.'}</p><p>To expand a low pixel into its 2×2 high-resolution cell without materializing an upsampled image, shuffle from lane <code>(L&amp;3) | ((L&gt;&gt;1)&amp;4) | ((tile&amp;1)×8) | (rowHalf×16)</code>. Select low-row index <code>tile//2</code>. The lane bit pattern combines unchanged channel ownership with half-resolution pixel ownership. For lane 13, tile 0, rowHalf 0, the source is lane 5; rowHalf 1 uses lane 21. For tile 1 the corresponding lanes are 13 and 29.</p><p>The merge is <code>HalfFma(skip,adapterScale,HalfMul(low,inputScale))</code>. First round the low product to Half, then fuse the skip product with its addition. Computing two independently rounded products, fusing the low side instead, or using FP32 for the sum changes the numerical contract. Keep the resulting raw Half merge for the FFN residual, while the matrix-input copy is published to the selected precision.</p>'''
    body+=excerpt(path,'// Load low channel planes','// The complete fused', 'Native plane loads, register upsampling and rounded merge')
    body+=svg('Nearest expansion and raw residual lifetime','0 0 920 270','''<rect class="storage" x="15" y="20" width="265" height="90" rx="8"/><text class="label" x="30" y="50">Low C32 channel planes</text><text class="small" x="30" y="83">global load → decode → shuffle</text><rect class="storage" x="15" y="148" width="265" height="90" rx="8"/><text class="label" x="30" y="179">Full-resolution skip</text><text class="small" x="30" y="211">global uint4 → Half pair</text><path class="edge" d="M285 62 H345 V117 H390"/><path class="edge" d="M285 189 H345 V150 H390"/><rect class="compute" x="400" y="80" width="250" height="110" rx="8"/><text class="label" x="415" y="111">HalfMul low × scale</text><text class="small" x="415" y="142">then HalfFma skip × scale</text><text class="small" x="415" y="170">raw Half merge stays live</text><path class="edge" d="M655 113 H700 V63 H733"/><path class="edge" d="M655 154 H700 V206 H733"/><text class="label" x="742" y="68">FFN operands</text><text class="small" x="742" y="97">published copy</text><text class="label" x="742" y="208">FFN residual</text><text class="small" x="742" y="235">raw Half copy</text>''')
    body+=f'''<p>The output profile has its own offsets: input scale {8272 if fp8 else 16464}, adapter scale {8336 if fp8 else 16528}, and final Half head {20784 if fp8 else 33072}, all measured in bytes from the packed record base. The full record size is {21808 if fp8 else 34096} bytes. Each scale group uses <code>16×outputGroup+4(L%4)</code>, selecting the two channels owned by that lane in the accumulator. Read the exact profile before writing any pointer arithmetic.</p>'''+code(BASE+'frontend_profiles.cuh',31,42,'Output-specific weight and scale offsets')
    from lessons_windows import c32_core_lesson
    body+=c32_core_lesson(fp8,'the raw Half merged input r_RawInput',path)
    body+='''<h2 id="head">Apply the Half head before releasing the attention tile</h2><p>The fused transformer produces a raw Half 16×32 tile. Immediately multiply it by the head weights with two K16 Half instructions, accumulating into one 16×8 instruction tile. The model consumes four head channels. The stored Half weight panel is padded to 16 columns: each K16 slice occupies 512 bytes, with each lane loading a uint4. This kernel selects only the first two words for the first N8 instruction, and the pixel gather consumes only the four useful channels from its eight-column result. Weight loads use <code>HeadOffset+reductionChunk×512+L×16</code> and select the first two words as the B fragment. No FP8 publication is inserted between the raw transformer output and this Half head.</p><p>Store the two output words per tile in <code>r_Head[4][2]</code>. Applying the head as soon as an attention tile finishes shortens the lifetime of the larger C32 output. The later image loop needs only this small four-channel head representation. At this point the kernel has still not allocated a global head tensor.</p>'''
    body+=excerpt(path,'// Apply the output head','// Decode the learned head','Head weights and two Half reduction chunks')
    body+='''<h2 id="head-gather">Transpose lane-owned head words into pixels</h2><p>Each image lane must own RGBA-like head channels for one pixel, while MMA distributed those channels across lanes. For each tile row (0 or 1), set <code>rowHalf=L&amp;1</code>, <code>tile=(L&gt;&gt;1)&amp;1</code>, and <code>src=((L&amp;7)&lt;&lt;2)|(L&gt;&gt;3)</code>. Four shuffles read the appropriate tile/row words from <code>src</code>, <code>src XOR 1</code>, <code>src XOR 2</code> and <code>src XOR 3</code>. Select a neighboring word pair with <code>wordIndex=((L&gt;&gt;3)&amp;1)|((L&gt;&gt;3)&amp;2)</code>. Unpack its four Half values into float.</p><p>The pixel destination is <code>x=ox+4(L//16)+(L%4)</code>, <code>y=oy+(L%16)//4+4×tileRow</code>. For lane 13, tileRow 0: <code>(x,y)=(ox+1,oy+3)</code>, <code>rowHalf=1</code>, <code>tile=0</code>, source lane 21, and wordIndex 1. This thread obtains the four head values for that one pixel; it is no longer interpreted as four unrelated accumulator elements.</p>'''
    body+=excerpt(path,'// Gather the four Half head channels','const bool bValidPixel', 'Register transpose, pixel coordinates and head unpacking')
    body+='''<h2 id="compose">Compose neural color, display color and optional history</h2><p>First reject coordinates outside the physical output extent. A second predicate distinguishes renderer-valid pixels inside the padded field. If a color texture exists and this pixel is valid, each RGB channel becomes <code>fma(OutputScale,headRGB,fma(currentRGB,0.125,−0.0625))</code>. Otherwise use <code>OutputScale×headRGB</code>. Initially alpha is zero. Display mode converts RGB with <code>clamp(8×color+0.5,0,1)</code> and sets alpha to one.</p><p>An optional two-byte Half scalar controls the maximum history blend. If absent, it is one. The source uses an unordered equality test against infinity on the absolute FTZ bit pattern, sending infinity and unordered values to zero; other values are clamped to [0,1]. Do not replace that exceptional-value branch with an ordinary host comparison.</p><p>History blending occurs only in display mode, with history and motion textures present, a renderer-valid pixel, and a positive blend scale. Sample motion through its transform. If <code>bApplyMotion</code> is set, form previous UV by FMA with MotionScale; otherwise retain current UV. Use the same five-tap reconstruction shown below. The fourth head channel is a gate: <code>e=exp2_approx(headW×(−log2(e)))</code>, <code>w=clamp(rcp_approx(1+e)×blendScale,0,1)</code>. Blend RGB as <code>fma(w,history−color,color)</code>. The clamp precedes blending; there is no new RGB clamp after that FMA in the source.</p>'''
    body+=excerpt(path,'if (Parameters.ColorTexture','NativeSurface2d', 'Exact composition branches and gate arithmetic')
    body+=history_filter()
    body+=svg('Per-pixel output composition','0 0 930 300','''<rect class="tensor" x="15" y="20" width="245" height="95" rx="8"/><text class="label" x="30" y="51">Half head → float4</text><text class="small" x="30" y="84">RGB residual + W gate</text><path class="edge" d="M265 64 H320"/><rect class="compute" x="330" y="20" width="265" height="95" rx="8"/><text class="label" x="345" y="51">Current-color residual</text><text class="small" x="345" y="84">then optional display conversion</text><path class="edge" d="M600 64 H656 V163"/><rect class="storage" x="15" y="175" width="245" height="95" rx="8"/><text class="label" x="30" y="206">History + motion textures</text><text class="small" x="30" y="239">transform → five-tap RGB</text><path class="edge" d="M265 220 H320"/><rect class="compute" x="330" y="175" width="265" height="95" rx="8"/><text class="label" x="345" y="206">Gate W → sigmoid × scale</text><text class="small" x="345" y="239">valid display pixels only</text><path class="edge" d="M600 220 H638"/><rect class="storage" x="648" y="175" width="265" height="95" rx="8"/><text class="label" x="663" y="206">float4 output surface</text><text class="small" x="663" y="239">RGB blend + fixed mode alpha</text>''')
    body+='''<h2 id="surface">Write the surface and close the storage lifetime</h2><p><code>NativeSurface2d</code> writes four float bit patterns to the CUDA surface at the selected pixel. The helper passes x unchanged to <code>sust.p.2d.v4.b32.zero</code>. Its <code>.p</code> form uses a surface-sample coordinate, so x selects a float4 pixel directly; there is no explicit multiplication by 16. The helper parameter name ByteCoordinateX and its nearby byte-offset comment are misleading for this formatted instruction. <a href="https://docs.nvidia.com/cuda/parallel-thread-execution/#surface-instructions-sust">The PTX surface-store specification</a> distinguishes this sample addressing from the byte addressing of <code>sust.b</code>. The surface is backed by a CUDA array, not the low-field or skip pointer. The host copies initial output contents into that array before launch and copies it back afterward, preserving pixels untouched by the configured window origin and bounds.</p><p>No explicit shared-memory allocation is required by this output entry: native inputs are gathered through global loads and warp shuffles, and the transformer/head fragments remain thread-local. Its source-level register limit is 168. Cache hints on skip and weight reads express caching policy, not visibility between launches. The host's stream ordering handles prior producers and the surface copyback.</p>
<h2 id="rebuild">Reconstruct the output kernel in stages</h2><ol><li>Implement a scalar nearest-neighbor expansion and exact rounded merge. Verify low-plane and skip-tile loads independently with coordinate/channel-coded values.</li><li>Derive the expansion shuffle lane equation and compare each Half pair against the scalar merge before enabling the fused block.</li><li>Implement the complete local FFN/attention sequence above with the output-specific record offsets.</li><li>Apply the Half head to one raw output tile, then implement the four-shuffle transpose into per-pixel head values.</li><li>Add composition one branch at a time: current-color residual, display conversion, exceptional blend scalar handling, history reconstruction, gate, and surface store.</li></ol><p>The useful optimizations follow the data lifetimes: upsample in registers, retain raw Half residuals, avoid materializing head and score tensors, reuse loaded weights across four tile fragments, and apply the small head before advancing to the next attention tile. Each optimization is subordinate to the actual precision and lane contracts.</p>
<h2 id="tests">Test the merged features and final pixels separately</h2><ol><li>Use a low-resolution impulse and a coordinate-coded skip. Check exactly which 2×2 high-resolution pixels inherit the low value at each origin phase.</li><li>Choose merge operands whose two possible FMA associations differ. Compare against the low-product-first Half expression.</li><li>Use sparse head weights to isolate channels 0,1,2 and 3. Check the head transpose with all 32 lanes and both tile rows.</li><li>Exercise display on/off, color absent/present, history or motion absent, motion application off, blend scale zero/one/infinite/NaN, and valid extents smaller than physical extents.</li><li>Compare the five-tap filter separately using an image ramp and a sharp impulse; confirm clamped sample coordinates and the retained-weight normalization at borders.</li><li>Put canaries around backing tensors and verify untouched physical pixels retain their initial values when the launch phase omits them.</li></ol><p>The source walkthrough does not replace GPU correctness tests or register/spill measurements. No new performance result is asserted by these documentation changes.</p>'''
    body+='''<p>For a concrete final-pixel oracle, set the low field, skip, all learned matrices and biases to zero, set scales to one, and disable color and history textures. Non-display mode must write RGBA=(0,0,0,0); display mode must write (0.5,0.5,0.5,1) at every valid physical pixel. An absent blend scalar defaults to one, whereas a supplied Half NaN, +infinity or −infinity disables history through the exceptional-value branch. With history disabled, those scalar cases must leave the same final pixels as the baseline above.</p>'''
    return dict(name=name,title=f'{p} output frontend: decoder features to final pixels',summary='Derive plane loads, nearest expansion, the complete C32 transformer, Half head lane transpose, temporal gate and output-surface publication.',family='Output frontend',body=body)


def build_lessons(inventory):
    result=[]
    for name,entry in inventory['entries'].items():
        if name.startswith('input_preprocess_'):result.append(preprocess(name,entry))
        elif name.startswith('output_window_postprocess_'):result.append(postprocess(name,entry))
    return result
